### ISSUE TITLE
revive curl api

### ISSUE THREAD

**Issue by pmikova** [judovana/jenkins-scm-koji-plugin#104]
curl api is now dead, and imho is crucial
In adition we need a filename verification in it: parse  which parse the filename or return non 200 on failure
Also we need new getJobsForNvr(a?)

J.

**Comment by judovana** [comment]
commit 796fe0ca6cb0c4fdfa5e68e01f5488babaeab071 (HEAD -> master, origin/master, origin/HEAD)
Author: Jiri <jvanek@redhat.com>
Date:   Tue Mar 3 07:53:45 2020 +0100

    Temporarily disabled curl api

diff --git a/jenkins/custom_run_wrappers/parts/initMachines.sh b/jenkins/custom_run_wrappers/parts/initMachines.sh
index 94b983a9..55375524 100644
--- a/jenkins/custom_run_wrappers/parts/initMachines.sh
+++ b/jenkins/custom_run_wrappers/parts/initMachines.sh
@@ -110,6 +110,8 @@ DESTINATION=$master_user@$master
 # however odin have its own instantion of fake-koji
 # if some fake-koji instance will have different paths, then UPSTREAM_REPOS_PATH/DESTINATION_PATH must go away
 # and job must determine which fake-koji it is speaking too, and ask it for its settings
-DESTINATION_PATH=`curl -s http://$hydra/get?root`
-UPSTREAM_REPOS_PATH=`curl -s http://$hydra/get?repos`
+#DESTINATION_PATH=`curl -s http://$hydra/get?root`
+#UPSTREAM_REPOS_PATH=`curl -s http://$hydra/get?repos`
+DESTINATION_PATH=/mnt/raid1/local-builds
+UPSTREAM_REPOS_PATH=/mnt/raid1/upstream-repos
 
diff --git a/otool/pull.sh b/otool/pull.sh
index 424315a5..2614838f 100644
--- a/otool/pull.sh
+++ b/otool/pull.sh
@@ -366,7 +366,8 @@ fi
 if [ ! "x$NO_UPLOAD" == "xTRUE"  ] ; then
   if [ "x$PORT" == "x" ] ; then
     # from initMachines
-    PORT=`curl http://$hydra/get?uport`
+    #PORT=`curl http://$hydra/get?uport`
+    PORT=9822
   else
     PORT=$PORT
   fi
