### ISSUE TITLE
generate update job for platforms

### ISSUE THREAD

**Issue by pmikova** [judovana/jenkins-scm-koji-plugin#107]
and better, not by platform, but by its vm flag

**Comment by oklinov** [comment]
another flag into the provider array (upgradable)

**Comment by judovana** [comment]
First implementation of xml tempaltes:

https://github.com/judovana/jenkins-scm-koji-plugin/commit/0e522a86dad2d80646e1d3fe6242a6ab61031cbb

todo is to push them to jenkins and to fix the script for real HW

**Comment by judovana** [comment]
alive on hydra. Tested for vms, HW slaves not yet implemented
