### ISSUE TITLE
another testvariant - agent type

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#108]

**Comment by judovana** [comment]
linuxagent and winagent would be a choices I guess

**Comment by oklinov** [comment]
maybe add duplicate testsuites with custom variables? which will be implemented soon

**Comment by judovana** [comment]
As only tck and reproducers security are affected by this, I'm inclining to dupliated framework, rather then globa variant, which only two suites will use

**Comment by judovana** [comment]
otool part is done; missing bash part

**Comment by oklinov** [comment]
Done
