### ISSUE TITLE
platforms have duplicated setup by provider

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#110]
Usually the os.arch.provider are same, all except provider field. Maybe to change it that providers are an array for platform?

**Comment by judovana** [comment]
Such setup may invalidate the eal HW node usage. If so, then better keep duplicated tags.

**Comment by judovana** [comment]
Also vm-nodes are not compatible with this change

**Comment by oklinov** [comment]
platform config -> providers: [ { id: "", vmNodes: [""], hwNodes: [""] } ]
