### ISSUE TITLE
test-only buildpltform is misleading

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#111]
a) it have to be combobox
b) plain eg:e7-x64 canbe misleading
c) to allow select from full eg:e7-x64.vagrant or eg:e7-x64.beaker do not have sense

The only thing what is deducted from it is TAG

thus I suggest following:
1) In that field show what it is - eg e7-x64
2) in config save correct if - rg e7-x64.vagrant
3) in combobox selection show e7-x64 ( tags )

If   different field and list values are problem, I would vote for  e7-x64 ( tags ) for both.

**Comment by oklinov** [comment]
There should be shown tags of a platform in the main tree (maybe?)
