### ISSUE TITLE
Unknown build platform

### ISSUE THREAD

**Issue by RadoslavCap** [judovana/jenkins-scm-koji-plugin#113]
I've tried to create a new test project with settings saved in configs history named radek_win_test*

I've met a few errors:

- build platform is refused, evolution of my attempts is visible in diffs between radek_win_test.json - radek_win_test1.json, radek_win_test1.json - radek_win_test2.json etc.

- even if build platform is refused configuration is probably stored because after an editation I'm getting name exists

**Comment by judovana** [comment]
The platform you were searching was 
  w2019.x64
-1 ondra :)

**Comment by RadoslavCap** [comment]
Nice, it's working with dot! We can move forward.

**Comment by judovana** [comment]
yup. Please not that this must change., Ondro must add a combobox.

**Comment by judovana** [comment]
So there will be very likly full ID and visible lilkly the gat - see https://github.com/judovana/jenkins-scm-koji-plugin/issues/111

**Comment by oklinov** [comment]
the text field will be removed in favor of build platform plus (jvanek understands)
