### ISSUE TITLE
koji arch and job-view arch should be distinguished

### ISSUE THREAD

**Issue by RadoslavCap** [judovana/jenkins-scm-koji-plugin#117]
We generated job from platform with value "x64". Job was properly generated with this value. Question and note for @judovana is, why it was working for him in previous testing.

**Comment by judovana** [comment]
I would suggest to have two fields in paltform config
kojiArch
and real arch.
if one of them wouldbe missing, then the second one woudl be used. Only windows will actually have two at the end.

**Comment by RadoslavCap** [comment]
Sounds good.

**Comment by oklinov** [comment]
Fixed in https://github.com/judovana/jenkins-scm-koji-plugin/commit/cda94c245d1f36da59dd2b20c12dabe371f3d8b4
