### ISSUE TITLE
Backup previously generaterd configuration

### ISSUE THREAD

**Issue by RadoslavCap** [judovana/jenkins-scm-koji-plugin#121]
As I observe current stability of oTool - it would be fine to have backup configuration when configuration is regenerated or updated.

**Comment by judovana** [comment]
Considering that the some of the configs are read-only onlong run, but some subjkect of quick change, only proper backuping of configs to jom via our old tool is correct.

In meantime I had added possibility to have them pushed in our scripts, and sycning script can backup and restore from our repo

the key for this is UPDATE_OTOOLCFGS, but hopefully it will nto be used ever
