### ISSUE TITLE
Jenkins CLI

### ISSUE THREAD

**Issue by oklinov** [judovana/jenkins-scm-koji-plugin#123]
When running tests, Jenkins CLI throws exceptions: "Failed to get the session". Could you create some mockup?

**Comment by judovana** [comment]
We already spoken about this. There are two levels of protection against this in code:

1) you use assume(haveJenkins)
  - this will disabe the test if there isno local jenkins
  - this usable only for tests which do not need to check jenkins api call results

2)  anyu test dealing with jobs generation, and not caring about jenkins ap call, can disable it before test/file and enable it after. You do that eg like this:
before:  JenkinsCliWrapper.killCli();
fianlly:   JenkinsCliWrapper.reinitCli();


eg: JDKTestProjectManagerTest

**Comment by judovana** [comment]
please close if this is not enough. If not, what more do you wish?

**Comment by oklinov** [comment]
That will do...closing this issue
