### ISSUE TITLE
connect  varians by "." instead of "-" as"-" is used everywhere as group delimiter

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#156]

**Comment by judovana** [comment]
churn-jp8-ojdk8~rpms-el7.x86_64-release-jre-headless-el7.x86_64.beaker-x11-defaultgc-legacy-lnxagent-jfroff
->

churn-jp8-ojdk8~rpms-el7.x86_64-release.jre.headless-el7.x86_64.beaker-x11-defaultgc.legacy.lnxagent.jfroff

wdyt?

**Comment by judovana** [comment]
it is already used in platform and in R(from NVR)

**Comment by oklinov** [comment]
Done
