### ISSUE TITLE
missing logic to bump platform

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#159]
note, that this really should persist old job, so job should be renamed

**Comment by judovana** [comment]
alo may be worthy to make it generic, so eg bumpof java plarform version is possible for some given project (jdk latest, ojdkX)

**Comment by judovana** [comment]
bump os/hw platform, or name or url otr whatever, have jsut two params - original value, new value
However pump of javaplatform have actually four params.  jp and package of old, and jp and package of new.
This directly mirror the datastrcutres it is basedon - jp and paclage names are part of jp.json

If the package will be made optional, then it ithave to bump only from default package of old java platfrom to defualt package of new java paltform

eg
xyz.f31.x64.blah ->   curl://bump?from=f31.x64&to=f32.x64  => xyz.f32.x64.blah
xyz.jp11.ojdk11.blah ->   curl://bump?from=jp11&to=jp12  => xyz.jp12.ojdk12.blah
xyz.jp11.ojdkWhau.blah ->   curl://bump?from=jp11&to=jp12  => error, as ojdkWahu is not default package of jp11
xyz.jp11.ojdkWhau.blah ->   curl://bump?from=jp11&frompkg=Whau&to=jp12&topkg=Whaaaa  =>  xyz.jp12.ojdkWhaaaa.blah where  Whaaaa is some pkg under the jp12

**Comment by judovana** [comment]
An optional parameter to select what projects to bump is also necessary.
Where hw/os paltform bump will msot likely affect all jobs, the java paltfrom bump will affect only one or two or three projects...

**Comment by oklinov** [comment]
Done
