### ISSUE TITLE
add view generation

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#160]
per task
per task x jdk major
per task x os
templates from tasks
anything else in dark future

update via ssh's 
 update-view
    Updates the view definition XML from stdin. The opposite of the get-view command.

**Comment by judovana** [comment]
per project
perproject x os

**Comment by judovana** [comment]
per os pet suite type
 - the testsuites can always show jtregs
 -  the benchmarks.. welll it samore tricky but possible

**Comment by judovana** [comment]
ssh -p 9999 localhost help 2>&1 | grep view
```
  add-job-to-view
    Adds jobs to view.
  create-view
    Creates a new view by reading stdin as a XML configuration.
  delete-view
    Deletes view(s).
  get-view
    Dumps the view definition XML to stdout.
    Lists all jobs in a specific view or item group.
  remove-job-from-view
    Removes jobs from view.
  update-view
    Updates the view definition XML from stdin. The opposite of the get-view command.
```


 ssh -p 9999  localhost get-view specjbb
```
<?xml version="1.1" encoding="UTF-8"?>
<hudson.model.ListView>
  <name>specjbb</name>
  <filterExecutors>false</filterExecutors>
  <filterQueue>false</filterQueue>
  <properties class="hudson.model.View$PropertyList"/>
  <jobNames>
    <comparator class="hudson.util.CaseInsensitiveComparator"/>
  </jobNames>
  <jobFilters/>
  <columns>
    <hudson.views.StatusColumn/>
    <hudson.views.WeatherColumn/>
    <hudson.views.JobColumn/>
    <hudson.plugins.report.genericchart.GenericChartColumn plugin="jenkins-report-generic-chart-column@0.1-SNAPSHOT">
      <fileNameGlob>specjbb2015-C-*.raw</fileNameGlob>
      <key>jbb2015.result.metric.max-jOPS</key>
      <limit>15</limit>
      <columnCaption>Max jOPS</columnCaption>
      <chartColor>#00FF00</chartColor>
      <resultsBlackList></resultsBlackList>
      <resultsWhiteList></resultsWhiteList>
      <rangeAroundWlist>0</rangeAroundWlist>
    </hudson.plugins.report.genericchart.GenericChartColumn>
    <hudson.plugins.report.genericchart.GenericChartColumn plugin="jenkins-report-generic-chart-column@0.1-SNAPSHOT">
      <fileNameGlob>specjbb2015-C-*.raw</fileNameGlob>
      <key>jbb2015.result.metric.critical-jOPS</key>
      <limit>15</limit>
      <columnCaption>Critical jOPS</columnCaption>
      <chartColor>#0000FF</chartColor>
      <resultsBlackList></resultsBlackList>
      <resultsWhiteList></resultsWhiteList>
      <rangeAroundWlist>0</rangeAroundWlist>
    </hudson.plugins.report.genericchart.GenericChartColumn>
    <hudson.views.LastFailureColumn/>
    <hudson.views.LastSuccessColumn/>
    <hudson.views.LastDurationColumn/>
    <hudson.views.BuildButtonColumn/>
  </columns>
  <includeRegex>^specjbb-.*</includeRegex>
  <recurse>false</recurse>
</hudson.model.ListView>
```

So it is super easy. Will add  contnet of ```  <columns>``` element as second tempalte to the task
Something to thing about -
```  <filterExecutors>false</filterExecutors>
  <filterQueue>false</filterQueue> ```

Will set them to true, ok?

Similarly per-projects view, will be fully hardcoded tempale:
sh -p 9999  localhost get-view ~ojdk11~shenandoah~upstream~cpu
```
<?xml version="1.1" encoding="UTF-8"?>
<hudson.model.ListView>
  <name>~ojdk11~shenandoah~upstream~cpu</name>
  <filterExecutors>true</filterExecutors>
  <filterQueue>true</filterQueue>
  <properties class="hudson.model.View$PropertyList"/>
  <jobNames>
    <comparator class="hudson.util.CaseInsensitiveComparator"/>
  </jobNames>
  <jobFilters/>
  <columns>
    <hudson.views.StatusColumn/>
    <hudson.views.WeatherColumn/>
    <hudson.views.JobColumn/>
    <hudson.views.LastSuccessColumn/>
    <hudson.views.LastFailureColumn/>
    <hudson.views.LastDurationColumn/>
    <hudson.views.BuildButtonColumn/>
  </columns>
  <includeRegex>.*-ojdk11~shenandoah~upstream~cpu-.*|pull-.*-ojdk11~shenandoah~upstream~cpu</includeRegex>
  <recurse>false</recurse>
</hudson.model.ListView>```


The major questionm is - what other views we need?

**Comment by judovana** [comment]
"The major questionm is - what other views we need?"
per task
per project
per task x platfomr
per project x platform

**Comment by RadoslavCap** [comment]
I'm using these views (filtered by OS == win) and I'm not sure how to fit it with previous comments.

Every view is splitted by priorities as defined here - https://docs.engineering.redhat.com/display/RHELPLAN/Test+jobs

**CPU views**
ojdk8-upstream
ojdk11-upstream
ojdk8-RH
ojdk11-RH

**ojdk11**
updates-upstream
updates-upstream-fastdebug
shenandoah-upstream
shenandoah-upstream-fastdebug
cpu-upstream
cpu-upstream-fastdebug
shenandoah-cpu-upstream-fastdebug
windows-redhat

**ojdk8**
jfr
jfr-fastdebug
upstream
upstream-fastdebug
dev-upstream
dev-upstream-fastdebug
aarch64-shenandoah
cpu-upstream
cpu-upstream-fastdebug

**ojdk7**
build-static

**Comment by judovana** [comment]
> I'm using these views (filtered by OS == win) and I'm not sure how to fit it with previous comments.
> 
> Every view is splitted by priorities as defined here - https://docs.engineering.redhat.com/display/RHELPLAN/Test+jobs
> 
> **CPU views**
> ojdk8-upstream
> ojdk11-upstream
> ojdk8-RH
> ojdk11-RH
> 
> **ojdk11**
> updates-upstream
> updates-upstream-fastdebug
> shenandoah-upstream
> shenandoah-upstream-fastdebug
> cpu-upstream
> cpu-upstream-fastdebug
> shenandoah-cpu-upstream-fastdebug
> windows-redhat
> 
> **ojdk8**
> jfr
> jfr-fastdebug
> upstream
> upstream-fastdebug
> dev-upstream
> dev-upstream-fastdebug
> aarch64-shenandoah
> cpu-upstream
> cpu-upstream-fastdebug
> 
> **ojdk7**
> build-static

Those are moreover done by per project and per project x platform. All except fastdebug.  I did not had any intentions to do a  whaever x per-build.variant.

Have you aleready  dound the fastdebug views usefull? From my point of view, I'm appreciating the to be visible next to the normla ones.

**Comment by RadoslavCap** [comment]
> Have you aleready dound the fastdebug views usefull? From my point of view, I'm appreciating the to be visible next to the normla ones.

Not yet.

I'm still not sure

**Comment by RadoslavCap** [comment]
Note from a discussion on irc: consider nested views, something like this - https://plugins.jenkins.io/nested-view/

**Comment by judovana** [comment]
first comit, which generates the matrix, and preview xml tempaltes:
https://github.com/judovana/jenkins-scm-koji-plugin/commit/c24b7b6cdc0059a84b6c655244956e2df8f4782e

todo, gui to allow set columns per task, and once done fill the columns, and once done, make the logic to push those to jenkins

**Comment by judovana** [comment]
alive on hydra
