### ISSUE TITLE
new xmlrpcapi rewrites build.xml

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#179]
new api checkout is mroe agresive then old one.
I'm just guessing, but it looks like it remove build.xml if no chnages are found.
This is making "build now" button very usles, as it depends on latest build.xml file.

**Comment by judovana** [comment]
generically thios this is severe, and is prohibiting any "build now action"
On old api, the build xml persists void pull
on new not.  This have to be fixed. Thougth on how to do thsi better?

how to reproduce:
  - crate new api job, which takes 1 minute with pooling of 2 minutes
 - click build now - it runs fine, because no processed.txt nor build xml exists

 - immediatley after itt is finished, click build now. Again it works Build xml is here, and proccessed.txt is here - build.xml is reused

 - after it is build wait for pull which finds nothing. In this scenario build.xml is rewritten.
 - as there is processed.txt and missing build.xml, pooling is invoked, but as there is  - after check agaisnt processed.txt - nothing to pull, builds fails.

**Comment by oklinov** [comment]
Fixed
