### ISSUE TITLE
migrate current execute bash to execute bash with timeout

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#189]
Currenlty otool generates execute bash.
To move it to bash with timeout requires https://plugins.jenkins.io/build-timeout/ and enhance otool to generate  tempalte for it insted palin bash.
In addition gui of task needs to be enhanced for timeout .. in hours?
exmapel job: http://jormungandr:8888/view/wildfly/job/wildfly-ojdk12-rhel7-x64-beaker/configure

implementation detail, if timeout is 0, use old approach, an 0 is the default

Alice, pelase provide list of timeouts per task...and well anything what can help to implement this.
Ondro, I will do that, but your review wil be still essential:(

**Comment by judovana** [comment]
If this should be super accurate we  can add an timeout factor to platform config
Thus eg tck suite will have timeout of 24 but on aarch64, whete modifier will be 0.5 it will result to 12
Or eg specjbb with timeout of 3 hours,  on ppc64le, where timeout will be 3,it will be 9 hours.

However, I'm against, as we probably need to keep this  per provider and simialrly...

**Comment by judovana** [comment]
https://docs.google.com/spreadsheets/d/1PMPFwwSg2SrS-AH5iOKXDh0cSPyVrHdMKlo7-c-yuVM/edit?ts=5e78da3f#gid=0

**Comment by pmikova** [comment]
> If this should be super accurate we can add an timeout factor to platform config

I strongly disagree. I think this is absolutely unnecessary and also could do more damage then good. This script is ment to kill stuck jobs. From my point of view, the window for timeout should be as wide as possible, to compensate for slower machines or timeouting tests. Only when it is clear, the job is stuck (several days of execution in most cases), it should be killed.

> Thus eg tck suite will have timeout of 24 but on aarch64, whete modifier will be 0.5 it will result to 12

This is a wasted effort, imho. Right now, we have about 0-10 stuck jobs each week. in 99% it is TCK, jtregs and reproducers.

> Or eg specjbb with timeout of 3 hours, on ppc64le, where timeout will be 3,it will be 9 hours.
> 
> However, I'm against, as we probably need to keep this per provider and simialrly...

From my point of view, a wide constraint given per testsuite is more than enough.

**Comment by judovana** [comment]
thanx. good for me :)

**Comment by judovana** [comment]
PR is now done

**Comment by judovana** [comment]
Pushed. Alice, feel free to enable it.
<=0 is the plain old shell
>0 is new timeouted one, with hours as unit

please close as ppropriate

**Comment by judovana** [comment]
alive on hydra
