### ISSUE TITLE
tarxz is hardcoded in buildhelpers

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#195]
Which efectively kills all suffix freedom new api so nicely introduced.
Buty what to do weith it is a question. HAve list of known suffixes? rteturn anything here? How with future multiple files support?

**Comment by judovana** [comment]
@oklinov  IS it already fixed?

**Comment by oklinov** [comment]
This should be fixed. But I haven't tested it.
