### ISSUE TITLE
Add views fro variants

### ISSUE THREAD

**Issue by RadoslavCap** [judovana/jenkins-scm-koji-plugin#210]
Consider to add view for variants. Current jfr would be helpfull but it won't by only one.

**Comment by judovana** [comment]
As varaint x variant is simply to huge  to generate as views,  I'm, thinking about non-combined test-variant views only: With non-empty switch, it should add views like shenandoah, defaultgc, fips, legacycrypto....

**Comment by judovana** [comment]
pushjed
