### ISSUE TITLE
Waiving table - add escape to close details popup

### ISSUE THREAD

**Issue by RadoslavCap** [judovana/jenkins-scm-koji-plugin#245]
It would be useful to add possibility to close details popup with Esc.

**Comment by judovana** [comment]
Should be easy to add. PR?-)

**Comment by judovana** [comment]
Done - https://github.com/judovana/jenkins-scm-koji-plugin/pull/244/commits/b30f1d54c9714fcf0b64402cccec49222464ac54
had it in mind since origin.
