### ISSUE TITLE
Waiving table - forward/backward functionallity

### ISSUE THREAD

**Issue by RadoslavCap** [judovana/jenkins-scm-koji-plugin#246]
It would be useful to have possibility to move forward/backward in details view.

**Comment by judovana** [comment]
ha! that would be indeed uperuseful

**Comment by judovana** [comment]
https://github.com/judovana/jenkins-scm-koji-plugin/pull/244/commits/7ca9be98fda4d30e0d6651eb19c3b6ebce4db58f
