### ISSUE TITLE
test-only jobs have double dash in names

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#79]
eg:
dacapo_test-jdk8-jdk8~rhel6-el6.x86_64--el6.x86_64.vagrant-x11-shenandoah

Obviously missing build paltform :)

**Comment by oklinov** [comment]
@judovana @pmikova can one of you have a look at this? The job name is generated in org.fakekoji.jobmanager.model.TestJob#toString

**Comment by judovana** [comment]
Imho the double slash is only output of errornous input, when build or tests variants results to array of zero members. Imho it can not happen.

**Comment by judovana** [comment]
Btw, see https://github.com/judovana/jenkins-scm-koji-plugin/pull/91
Maybe we can use shortened name also for regular jobs names....

**Comment by judovana** [comment]
so this is happening only in  t test-only jobs.  @oklinov  is there way how to distinguish them?

**Comment by judovana** [comment]
See https://github.com/judovana/jenkins-scm-koji-plugin/pull/91/commits/67467c10ed3553761e20999fb22be58e81b4b460

**Comment by oklinov** [comment]
There is, TaskJob has a field named projectType...but you can just check whether buildVariants is empty or not

**Comment by judovana** [comment]
ok, so then - would  you rather see ti if-outed or sanitized as I did in the PR?

**Comment by judovana** [comment]
fixed via https://github.com/judovana/jenkins-scm-koji-plugin/commit/67467c10ed3553761e20999fb22be58e81b4b460
