### ISSUE TITLE
Config directories should match gui tab names

### ISSUE THREAD

**Issue by pmikova** [judovana/jenkins-scm-koji-plugin#82]
Hi,

there are tabs in the app, that contain the configuration (JDKPROJECTS, JDKTESTPROJECTS, PRODUCTS, TASKVARIANTS...), but it does not match the contents of config directory:
buildProviders
jdkTestProjects
platformProviders
platforms
products
projects
tasks
taskVariants

I propose to change "projects" to "jdkProjects" to avoid confusion (as I was when I was trying to find the config files).

Thanks!

**Comment by judovana** [comment]
Afaik this is fixed, right?
