### ISSUE TITLE
Provide support for java-latest-openjdk and epel

### ISSUE THREAD

**Issue by pmikova** [judovana/jenkins-scm-koji-plugin#85]
Hi,

so we have product for OpenJDK 13, but the package name in this case is java-latest-openjdk. This causes the builds not be pulled from brew properly.

Test-only package should have override option for package name (jvanek).

Another issue is, current platforms  do not support epel7.* and epel8.* tags. When I try to edit platform, error with no explanantion occurs and the js console is empty.

Thanks!

**Comment by judovana** [comment]
duplicate of https://github.com/judovana/jenkins-scm-koji-plugin/issues/96
