### ISSUE TITLE
Generated machine names are invalid - probably too long

### ISSUE THREAD

**Issue by pmikova** [judovana/jenkins-scm-koji-plugin#86]
There is a box with generated name:
==> default:  -- Name:              reproducers_regula-jdk13-jdk13rhel7-el7.x86_64--el7.x86_64.vagrant-x11-shenandoah_default

Call to virDomainCreateWithFlags failed: Invalid machine name

Either the name is too long, or some special characters are not passing the check.
And from what I found: https://github.com/vagrant-libvirt/vagrant-libvirt/issues/545
Looks like  name.length < 60 characters is the limit. The name above has 89.

Thanks!

**Comment by judovana** [comment]
We likly have to fix this in bash call
My suggestion is  based on currentl nto existing OTOOL_variables
OTOOL_VM_NAME-OTOOL_TESTSUITE-hashOfTrimed to30(JOB_NAME)

Where jobname is comming from jenkins, but canbe provided by OTOOL_JOBNAME too, as all OTOOL_ vars are comfortably provided


Another option may be otoolproviding OTOOL_VMHASH
Which  would I suggest similar to above, just more readable:
reproducers_regula-jdk13-jdk13rhel7-el7.x86_64--el7.x86_64.vagrant-x11-shenandoah_default
=>
el7.x86_64-reproducers_regula-vxsd-jdk13-hasOf20FromRest
where hasOf20FromRest is calcualted from  cut  build info of jdk13-jdk13rhel7-el7.x86_64 , or maye for safe, from whole original job name

Thoughts?

**Comment by judovana** [comment]
See https://github.com/judovana/jenkins-scm-koji-plugin/pull/91

**Comment by judovana** [comment]
Pushed otool part via  https://github.com/judovana/jenkins-scm-koji-plugin/commit/d2d38eb63d01255552fef7497b4f3c8e7acecc77
OTOOL_JOB_NAME_SHORTENED should be now used for machine name (if set) . All josb have to be regenerated now and support added to bash parts

**Comment by judovana** [comment]
I had pushed OTOOL_JOB_NAME_SHORTENED to oru vagrant files. I have to shorten the name to 50chars, as vagrant is suffixinf _default behind each name. I guess it is sum in total of 60

**Comment by judovana** [comment]
Please watch this an let me know if issues persists
