### ISSUE TITLE
missing crypot setup

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#90]
fips default legacy

**Comment by pmikova** [comment]
this is new test variant field (not just value for existing field as jfr)

**Comment by zzambers** [comment]
currently fips is controlled by ENABLE_FIPS=true env. variable

**Comment by judovana** [comment]
As only tck and reproducers security are affected by this, I'm inclining to dupliated framework, rather then globa variant, which only two suites will use

**Comment by judovana** [comment]
we agreed to not use the duplicated suites.
However default gc and default crypto is nto acceptable
default. Such comon word shold have taste of its type. eg defaultgc or systemcp

**Comment by judovana** [comment]
fips defaultcp legacy future

**Comment by judovana** [comment]
fips  future  defaultcp legacy

**Comment by judovana** [comment]
done; missing bash aprt for future and default (considering legacy as default)

**Comment by oklinov** [comment]
Done
