### ISSUE TITLE
test-only setup is missing packageName

### ISSUE THREAD

**Issue by judovana** [judovana/jenkins-scm-koji-plugin#96]

**Comment by oklinov** [comment]
packageName is included in product. Do we need packageNames other than those defined in products?

**Comment by judovana** [comment]
Well, yah...

java-1.8.0-ibm
java-1.8.0-openj9
java-11-openj9

icedtea-web
java mission control

openj9-openj9-8-rhel8
openj9-openj9-11-rhel8
openj9-openj9-11-rhel7
openj9-openj9-8-rhel7
redhat-openjdk-18-openjdk18-openshift
openjdk-openjdk-11-rhel7
(yah, there is really an os in the container names)

**Comment by pmikova** [comment]
Inner implementation is not exaclty friendly for this.
We relay on configs, where jdkMajor is tight with packageName and version. eg
{jdk11
11
java-11-openjdk}

We will continu to maintain openj9 as veriant of openjdk(same as zero, hotspot...), and any renaimngs will remain only for test only.
So for test only packages, selection of jdk major remains as is, but new field package name will be present. Unless empty, it will override the packaeName from the jdkMajor config.

this should enable openj9 and conatiner testing from koji, and keep buildability clear.

**Comment by oklinov** [comment]
We need to add container names and oracle jdks

**Comment by judovana** [comment]
have added currently known names
